---
- name: Converge (apply role with selected vars)
  hosts: runner
  become: true

  vars_files:
    - vars/common.yml

  pre_tasks:
    - name: Load extra vars
      ansible.builtin.include_vars: "{{ lookup('env', 'TEST_VARS_FILE') }}"
      when: lookup('env', 'TEST_VARS_FILE') is defined

  roles:
    - role: riemers.gitlab_runner
